//  INGREDIENTS
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const ADD_INGREDIENT_HANDLER = "ADD_INGREDIENT_HANDLER";
export const REMOVE_INGREDIENT_HANDLER = "REMOVE_INGREDIENT_HANDLER";
// PROCESS
export const START_PROCESS = "START_PROCESS";
export const FAIL_PROCESS = "FAIL_PROCESS";
//  PURECHASE_BURGER
// export const PURECHASE_BURGER_START = "PURECHASE_BURGER_START";
// export const PURECHASE_BURGER_FAILED = "PURECHASE_BURGER_FAILED";
export const PURECHASE_BURGER_SUCCESS = "PURECHASE_BURGER_SUCCESS";
export const PURECHASE_BURGER_INIT = "PURECHASE_BURGER_INIT";
//  FETCH_ORDERS
// export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
// export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
//  DELETE_ORDER
// export const DELETE_ORDER_START = "DELETE_ORDER_START";
// export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
