//  INGREDIENTS
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const ADD_INGREDIENT_HANDLER = "ADD_INGREDIENT_HANDLER";
export const REMOVE_INGREDIENT_HANDLER = "REMOVE_INGREDIENT_HANDLER";
// PROCESS
export const START_PROCESS = "START_PROCESS";
export const SUCCESS_PROCESS = "SUCCESS_PROCESS";
export const FAIL_PROCESS = "FAIL_PROCESS";
//  PURCHASE_BURGER
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";
//  FETCH_ORDERS
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
//  DELETE_ORDER
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
//  AUTH_START
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
